version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: multi-module-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-password" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  service-registry:
    build:
      context: .
      dockerfile: service-registry/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend

  my-app:
    build:
      context: .
      dockerfile: my-app/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      # Container-specific DB config (overrides application.properties)
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_USER_PASSWORD}
    networks:
      - backend

  demo-app:
    build:
      context: .
      dockerfile: demo-app/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data: